frontend_room_reservation:
  path: /_room_reservation/availability
  controller: Mindbird\Contao\RoomReservation\Controller\AvailabilityController::checkAvailability
  defaults:
    _scope: frontend
    _token_check: true
  methods: [POST]

