services:
  # Frontend modules
  Mindbird\Contao\RoomReservation\Controller\BookingController:
    arguments:
      - "@mindbird.contao.booking_service"
    tags:
      - { name: contao.frontend_module, category: miscellaneous }

  # Services
  mindbird.contao.booking_service:
    class: Mindbird\Contao\RoomReservation\Services\BookingService

  Mindbird\Contao\RoomReservation\Services\BookingService: '@mindbird.contao.booking_service'
